# Generated by Django 5.2.17 on 2026-09-10 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('birth_date', models.DateField(help_text='用於計算月齡，供問卷適用規則比對', verbose_name='出生日期')),
                ('medical_no', models.CharField(blank=True, db_index=True, help_text='院內識別碼；日後對接共用兒童主檔時作為接點', max_length=50, verbose_name='病歷號')),
                ('tracking_status', models.CharField(blank=True, db_index=True, help_text='例如：一般、氣喘追蹤、早療追蹤。第一階段先用自由文字，待兒科部確認可用值後再收斂', max_length=50, verbose_name='追蹤狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('guardian', models.ForeignKey(blank=True, help_text='家長端登入後據此判斷可填答哪些兒童的問卷', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='主要照顧者帳號')),
            ],
            options={
                'verbose_name': '兒童',
                'verbose_name_plural': '兒童',
                'ordering': ['name', 'birth_date'],
            },
        ),
    ]
