# Generated by Django 5.2.17 on 2026-09-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '問卷分類',
                'verbose_name_plural': '問卷分類',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例如 tier1', max_length=30, unique=True, verbose_name='代碼')),
                ('name', models.CharField(help_text='例如 Tier 1 日常低負擔健康檢核', max_length=100, verbose_name='名稱')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, verbose_name='應用定位說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '分層（Tier）',
                'verbose_name_plural': '分層（Tier）',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='問卷名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='questionnaires.category', verbose_name='分類')),
                ('tier', models.ForeignKey(blank=True, help_text='可留空：問卷不必然隸屬於某個 Tier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='questionnaires.tier', verbose_name='分層')),
            ],
            options={
                'verbose_name': '問卷',
                'verbose_name_plural': '問卷',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='版本號')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發布'), ('retired', '已停用')], default='draft', max_length=20, verbose_name='狀態')),
                ('change_note', models.TextField(blank=True, verbose_name='改版說明')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='停用時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questionnaires.questionnaire', verbose_name='問卷')),
            ],
            options={
                'verbose_name': '問卷版本',
                'verbose_name_plural': '問卷版本',
                'ordering': ['questionnaire', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '未完成'), ('completed', '已完成')], default='in_progress', max_length=20, verbose_name='狀態')),
                ('source', models.CharField(default='parent', help_text='家長／照顧者填報', max_length=50, verbose_name='資料來源')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='children.child', verbose_name='兒童')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='questionnaires.questionnaireversion', verbose_name='問卷版本')),
            ],
            options={
                'verbose_name': '填答紀錄',
                'verbose_name_plural': '填答紀錄',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='最小月齡')),
                ('max_age_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大月齡')),
                ('tracking_status', models.CharField(blank=True, help_text='留空表示不限；需與 Child.tracking_status 相符', max_length=50, verbose_name='追蹤狀態')),
                ('condition_json', models.JSONField(blank=True, default=dict, help_text='適用時期、填答頻率與填答時點等，例如 {"frequency": "daily"} 或 {"period": "first_visit"}。第一階段刻意先放 JSON 不另開欄位，待兒科部確認實際規則後再收斂', verbose_name='其他條件')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='questionnaires.questionnaireversion', verbose_name='問卷版本')),
            ],
            options={
                'verbose_name': '適用規則',
                'verbose_name_plural': '適用規則',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='題組名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='questionnaires.questionnaireversion', verbose_name='問卷版本')),
            ],
            options={
                'verbose_name': '題組',
                'verbose_name_plural': '題組',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500, verbose_name='題目')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='補充說明')),
                ('question_type', models.CharField(choices=[('single', '單選'), ('multi', '複選'), ('number', '數值'), ('text', '簡短文字'), ('scale', '量表'), ('datetime', '日期／時間')], max_length=20, verbose_name='題型')),
                ('required', models.BooleanField(default=True, verbose_name='必填')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('config', models.JSONField(blank=True, default=dict, help_text='依題型放置額外設定，例如數值題的 {"min": 35, "max": 42, "step": 0.1, "unit": "°C"}；量表題的 {"min": 0, "max": 10}。刻意用 JSON 而非開一堆欄位，避免為少數題型撐大資料表', verbose_name='題型設定')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.section', verbose_name='題組')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BranchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_operator', models.CharField(choices=[('eq', '等於'), ('neq', '不等於'), ('in', '屬於（逗號分隔多值）'), ('gt', '大於'), ('gte', '大於等於'), ('lt', '小於'), ('lte', '小於等於'), ('answered', '已作答（不論答什麼）')], default='eq', max_length=20, verbose_name='比較方式')),
                ('trigger_value', models.CharField(blank=True, help_text='比對 Option.value；數值題直接填數字；「已作答」不需填', max_length=200, verbose_name='觸發值')),
                ('action', models.CharField(choices=[('show', '顯示'), ('hide', '隱藏')], default='show', max_length=20, verbose_name='動作')),
                ('target_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by', to='questionnaires.question', verbose_name='目標題目')),
                ('trigger_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='questionnaires.question', verbose_name='觸發題目')),
                ('target_questionnaire', models.ForeignKey(blank=True, help_text='跨問卷／跨 Tier 承接。刻意指向問卷主檔而非特定版本，觸發時才取當下已發布的最新版', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by', to='questionnaires.questionnaire', verbose_name='目標問卷')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to='questionnaires.section', verbose_name='目標題組')),
            ],
            options={
                'verbose_name': '分支條件',
                'verbose_name_plural': '分支條件',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='選項文字')),
                ('value', models.CharField(help_text='存入填答紀錄的實際值，分支條件也比對此值', max_length=100, verbose_name='選項值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.question', verbose_name='題目')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
                'ordering': ['question', 'order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'value'), name='unique_option_value_per_question')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='依題型彈性存值：單選為字串、複選為陣列、數值為數字、日期為 ISO 字串', verbose_name='答案')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='作答時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.question', verbose_name='題目')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.questionnaireresponse', verbose_name='填答紀錄')),
            ],
            options={
                'verbose_name': '填答內容',
                'verbose_name_plural': '填答內容',
                'ordering': ['response', 'question__section__order', 'question__order'],
                'constraints': [models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='questionnaireversion',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'version_number'), name='unique_version_number_per_questionnaire'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['child', 'status'], name='questionnai_child_i_82e7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['version', 'status'], name='questionnai_version_ebf416_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('child', 'version'), name='one_in_progress_response_per_child_version'),
        ),
        migrations.AddConstraint(
            model_name='branchrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_question__isnull', True), ('target_questionnaire__isnull', True), ('target_section__isnull', False)), models.Q(('target_question__isnull', False), ('target_questionnaire__isnull', True), ('target_section__isnull', True)), models.Q(('target_question__isnull', True), ('target_questionnaire__isnull', False), ('target_section__isnull', True)), _connector='OR'), name='branchrule_exactly_one_target', violation_error_message='目標題組／目標題目／目標問卷必須且只能擇一填寫。'),
        ),
    ]
